// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOACBOIbjoMqXKEPq29yckTLJVUgBA6Yk',
    appId: '1:104422463003:web:ca2ffc04b410e2db3c0abe',
    messagingSenderId: '104422463003',
    projectId: 'ride-share-964903',
    authDomain: 'ride-share-964903.firebaseapp.com',
    storageBucket: 'ride-share-964903.firebasestorage.app',
    measurementId: 'G-SB761BHTGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUOTvZs3HmNgYPOFRwNpQDXHOYWf3TODE',
    appId: '1:104422463003:android:5b620e72c3418c903c0abe',
    messagingSenderId: '104422463003',
    projectId: 'ride-share-964903',
    storageBucket: 'ride-share-964903.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEoAU5-K50eLhag5Bwfj5PjDYx71CKmtc',
    appId: '1:104422463003:ios:9a53bd029bc8e9933c0abe',
    messagingSenderId: '104422463003',
    projectId: 'ride-share-964903',
    storageBucket: 'ride-share-964903.firebasestorage.app',
    iosBundleId: 'com.mobilex.rideShare',
  );
}
